import React, { createContext, useContext, useState, useEffect } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'Official Statewide / Institutional' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'राजभाषा / State Official' },
  { code: 'kht', name: 'Khortha', nativeName: 'खोरठा', region: 'Dhanbad, Bokaro, Hazaribagh, Ramgarh' },
  { code: 'nag', name: 'Nagpuri', nativeName: 'नागपुरी (सादरी)', region: 'Ranchi, Khunti, Latehar, Palamu' },
  { code: 'sat', name: 'Santali', nativeName: 'संताली (ᱥᱟᱱᱛᱟᱲᱤ)', region: 'Dumka, Sahibganj, Singhbhum' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'Dhanbad, Bokaro, Dumka, Jamtara' },
  { code: 'mun', name: 'Mundari', nativeName: 'मुंडारी', region: 'Khunti, Ranchi Tribal Blocks' },
  { code: 'ho', name: 'Ho', nativeName: 'हो (Ho)', region: 'East Singhbhum, West Singhbhum (Kolhan)' },
  { code: 'kru', name: 'Kurukh', nativeName: 'कुड़ुख़ (उरांव)', region: 'Latehar, Palamu, Gumla, Lohardaga' }
];

const translations = {
  en: {
    portalTitle: 'Smart Water Purification & Quality Monitoring Portal',
    deptTitle: 'Drinking Water & Sanitation Department • Govt. of Jharkhand',
    sihRef: 'Problem Statement: SIH26040 | Hardware & Sustainable IoT',
    publicView: 'Citizen / Public View',
    phedView: 'PHED Institutional Portal',
    liveStream: 'Live IoT Telemetry Active',
    offlineStream: 'Offline / Buffered Mode',
    safe: 'SAFE TO DRINK',
    unsafe: 'UNSAFE - DO NOT DRINK',
    offline: 'OFFLINE',
    lastChecked: 'Last Verified',
    unitLocation: 'Unit Location',
    parameters: 'Water Quality Parameters (BIS 10500 Standards)',
    phLabel: 'pH Balance',
    tdsLabel: 'Total Dissolved Solids (TDS)',
    turbidityLabel: 'Turbidity (Cloudiness)',
    tempLabel: 'Water Temperature',
    safeVerdict: 'Safe for Consumption',
    unsafeVerdict: 'Exceeds Permissible Limit',
    warningVerdict: 'Near Threshold Limit',
    history7Days: '7-Day Water Quality History',
    nearbyUnits: 'Nearby Safe Water Points in Your Block',
    publicAlerts: 'Public Health Advisories & Alerts',
    filterHealth: 'Filter Cartridge Health',
    cartridgeInstalled: 'Cartridge Installed',
    lastMaintenance: 'Last Maintained',
    recirculationLog: 'Autonomous Recirculation & Solenoid Valve Log',
    inletVsOutlet: 'Inlet (Raw Water) vs Outlet (Purified Water) Comparison',
    inlet: 'Inlet (Raw Water)',
    outlet: 'Outlet (Purified Water)',
    fleetOverview: 'State Fleet Overview',
    incidentLog: 'Incident & Alert Log',
    maintenanceTab: 'Maintenance Schedule',
    analyticsTab: 'District Analytics & Cost Reports',
    simulatorTab: 'ESP32 IoT Simulator & Sync',
    totalUnits: 'Total Monitored Units',
    safeUnits: 'Safe Units',
    unsafeUnits: 'Unsafe / Diverted',
    offlineUnits: 'Offline Units',
    purifiedToday: 'Purified Water Delivered Today',
    targetVolume: 'Daily Target Volume',
    exportCsv: 'Export Compliance CSV',
    acknowledge: 'Acknowledge Alert',
    resolve: 'Mark as Resolved',
    logMaintenance: 'Log Maintenance Action',
    costPerLitre: 'Cost per Litre vs RO Benchmark',
    waterRecovery: 'Water Recovery vs Reject Ratio',
    co2Saved: 'Solar Carbon Offset (Kg CO₂)',
    login: 'Official Login',
    logout: 'Logout',
    selectUnit: 'Select Monitoring Unit',
    searchPlaceholder: 'Search by District, Block, Panchayat, or Unit ID...',

    // Super Simple Citizen View Keys (English)
    selectedWaterPoint: 'Selected Water Station',
    stationCode: 'Station ID',
    safeWaterHero: '100% PURE & SAFE TO DRINK',
    unsafeWaterHero: 'CAUTION: DO NOT DRINK',
    offlineWaterHero: 'STATION OFFLINE',
    safeHeroSubtitle: 'Clean, sweet, and healthy water tested live by solar IoT sensors.',
    unsafeHeroSubtitle: 'Filter is recirculating water to remove dirt and impurities. Please wait.',
    offlineHeroSubtitle: 'Station telemetry is offline for routine maintenance. Check back shortly.',
    listenAudio: '🔊 Listen to Status Voice',
    howIsWaterTitle: 'How is the Water Right Now?',
    howIsWaterSubtitle: 'Easy to understand checks for children and families',
    simpleViewBtn: '😊 Simple View',
    detailedViewBtn: '📊 Exact Numbers',
    clarityTitle: 'Water Clarity',
    clarityBadge: 'Crystal Clean',
    clarityHeading: 'Crystal Clear & Pure',
    clarityDesc: 'No dirt, mud, or cloudiness in the water.',
    tasteTitle: 'Taste & Minerals (TDS)',
    tasteBadge: 'Sweet & Light',
    tasteHeading: 'Sweet, Light & Healthy',
    tasteDesc: 'Balanced natural minerals essential for bones and vitality.',
    balanceTitle: 'Natural Balance (pH)',
    balanceBadge: 'Balanced',
    balanceHeading: 'Not Acidic, Not Bitter',
    balanceDesc: 'Neutral pH balance that is gentle on stomach and digestion.',
    freshnessTitle: 'Water Freshness',
    freshnessBadge: 'Fresh & Cool',
    freshnessHeading: 'Cool & Refreshing',
    freshnessDesc: 'Fresh drinking water pumped directly from underground aquifer.',
    rulesTitle: '3 Simple Steps to Drink Clean Water',
    rule1Title: '1. Check Green Light',
    rule1Desc: 'Fill water only when the green SAFE signal is shown.',
    rule2Title: '2. Use Clean Container',
    rule2Desc: 'Always bring a washed bottle or covered bucket from home.',
    rule3Title: '3. Drink Directly (No Boiling Needed)',
    rule3Desc: 'This water is 100% purified by solar multi-barrier filtration.',
    weeklyTitle: 'Past 7 Days Water History',
    pureLabel: 'Pure',
    impureLabel: 'Impure',
    loadingHistory: 'Loading history...',
    caretakerTitle: 'Village Jal Sahiya Caretaker',
    caretakerDesc: 'In-charge of local water station cleanliness and maintenance.',
    callJalSahiya: 'Call Jal Sahiya Caretaker',
    nearestWaterTitle: 'Find Nearest Safe Water Point (Map)',
    nearestWaterSubtitle: 'Active and safe water stations in your block:',
    selectLocationTitle: 'Select Your Water Station',
    selectLocationSubtitle: 'Choose your district or village to view live sensor telemetry for that specific point:',
    autoDetectBtn: '📍 Auto-Detect Location',
    detecting: 'Detecting Location...',
    stationsLabel: 'Stations',
    speakingAudio: 'Speaking...',
    tdsMetricDesc: 'Healthy Minerals (BIS Limit ≤ 500)',
    phMetricDesc: 'Optimal Balance (BIS 6.5 – 8.5)',
    turbidityMetricDesc: 'Crystal Clear (BIS Limit ≤ 1.0)',
    tempMetricDesc: 'Fresh Drinking Water (10 - 35°C)'
  },
  hi: {
    portalTitle: 'स्मार्ट जल शुद्धिकरण एवं गुणवत्ता निगरानी पोर्टल',
    deptTitle: 'पेयजल एवं स्वच्छता विभाग • झारखण्ड सरकार',
    sihRef: 'समस्या विवरण: SIH26040 | सतत ऊर्जा एवं हार्डवेयर IoT',
    publicView: 'नागरिक / सार्वजनिक दृश्य',
    phedView: 'पीएचईडी विभागीय पोर्टल',
    liveStream: 'लाइव IoT टेलीमेट्री सक्रिय',
    offlineStream: 'ऑफलाइन / बफ़र मोड',
    safe: 'पीने के लिए सुरक्षित',
    unsafe: 'असुरक्षित - न पिएं',
    offline: 'ऑफलाइन',
    lastChecked: 'अंतिम परीक्षण समय',
    unitLocation: 'इकाई का स्थान',
    parameters: 'जल गुणवत्ता पैरामीटर (BIS 10500 मानक)',
    phLabel: 'pH संतुलन (अम्लता/क्षारीयता)',
    tdsLabel: 'कुल घुलित ठोस (TDS)',
    turbidityLabel: 'गंदलापन (Turbidity)',
    tempLabel: 'जल का तापमान',
    safeVerdict: 'पीने योग्य एवं सुरक्षित',
    unsafeVerdict: 'अनुमेय सीमा से अधिक',
    warningVerdict: 'चेतावनी सीमा के करीब',
    history7Days: 'पिछले 7 दिनों का गुणवत्ता इतिहास',
    nearbyUnits: 'आपके प्रखंड में निकटतम सुरक्षित जल केंद्र',
    publicAlerts: 'सार्वजनिक स्वास्थ्य सूचनाएं एवं अलर्ट',
    filterHealth: 'फ़िल्टर कार्ट्रिज का स्वास्थ्य',
    cartridgeInstalled: 'कार्ट्रिज स्थापना तिथि',
    lastMaintenance: 'अंतिम रखरखाव तिथि',
    recirculationLog: 'स्वचालित पुनर्चक्रण एवं सोलेनोइड वाल्व लॉग',
    inletVsOutlet: 'इनलेट (कच्चा पानी) बनाम आउटलेट (शुद्ध पानी) तुलना',
    inlet: 'इनलेट (कच्चा पानी)',
    outlet: 'आउटलेट (शुद्ध पानी)',
    fleetOverview: 'राज्य स्तरीय इकाई अवलोकन',
    incidentLog: 'घटना एवं अलर्ट लॉग',
    maintenanceTab: 'रखरखाव कार्यक्रम',
    analyticsTab: 'जिलावार विश्लेषण व लागत रिपोर्ट',
    simulatorTab: 'ESP32 IoT सिम्युलेटर व सिंक',
    totalUnits: 'कुल निगरानी इकाइयां',
    safeUnits: 'सुरक्षित इकाइयां',
    unsafeUnits: 'असुरक्षित / डायवर्टेड',
    offlineUnits: 'ऑफलाइन इकाइयां',
    purifiedToday: 'आज वितरित शुद्ध जल',
    targetVolume: 'दैनिक लक्ष्य मात्रा',
    exportCsv: 'अनुपालन रिपोर्ट CSV डाउनलोड करें',
    acknowledge: 'अलर्ट स्वीकार करें',
    resolve: 'समाधान के रूप में चिह्नित करें',
    logMaintenance: 'रखरखाव दर्ज करें',
    costPerLitre: 'प्रति लीटर लागत (RO की तुलना में)',
    waterRecovery: 'जल पुनर्प्राप्ति बनाम अपशिष्ट अनुपात',
    co2Saved: 'सौर कार्बन बचत (किलोग्राम CO₂)',
    login: 'विभागीय लॉगिन',
    logout: 'लॉगआउट',
    selectUnit: 'निगरानी इकाई चुनें',
    searchPlaceholder: 'जिला, प्रखंड, पंचायत या यूनिट आईडी द्वारा खोजें...',

    // Super Simple Citizen View Keys (Hindi)
    selectedWaterPoint: 'चुना हुआ जल केंद्र',
    stationCode: 'यूनिट कोड',
    safeWaterHero: '100% शुद्ध एवं सुरक्षित जल',
    unsafeWaterHero: 'सावधान! अभी पानी न पिएं',
    offlineWaterHero: 'स्टेशन अभी ऑफलाइन है',
    safeHeroSubtitle: 'यह पानी एकदम साफ़, मीठा और सेहतमंद है। बच्चे व बड़े सभी सीधे पी सकते हैं।',
    unsafeHeroSubtitle: 'मशीन पानी से गंदलापन और मिट्टी साफ़ कर रही है। थोड़ी देर रुकें।',
    offlineHeroSubtitle: 'स्टेशन टेलीमेट्री रखरखाव के लिए ऑफलाइन है। कृपया थोड़ी देर बाद देखें।',
    listenAudio: '🔊 आवाज़ में सुनें (Listen)',
    howIsWaterTitle: 'पानी कैसा है? (सरल भाषा में)',
    howIsWaterSubtitle: 'बच्चों और परिवारों के लिए 4 आसान पैमाने',
    simpleViewBtn: '😊 आसान दृश्य',
    detailedViewBtn: '📊 संख्या / Meters',
    clarityTitle: 'साफ़-सफ़ाई',
    clarityBadge: 'एकदम साफ़',
    clarityHeading: 'शीशे जैसा चमकदार व साफ़',
    clarityDesc: 'पानी में कोई धूल, मिट्टी या कचरा नहीं है।',
    tasteTitle: 'स्वाद व खनिज (TDS)',
    tasteBadge: 'स्वादिष्ट',
    tasteHeading: 'मीठा, हल्का और सेहतमंद',
    tasteDesc: 'शरीर के लिए जरूरी सही मात्रा में मिनरल्स मौजूद हैं।',
    balanceTitle: 'प्राकृतिक संतुलन (pH)',
    balanceBadge: 'संतुलित',
    balanceHeading: 'न खट्टा, न कड़वा - एकदम सही',
    balanceDesc: 'पेट और पाचन के लिए सबसे उत्तम pH संतुलन।',
    freshnessTitle: 'ताजगी व तापमान',
    freshnessBadge: 'ताज़ा व शीतल',
    freshnessHeading: 'पीने लायक ताज़ा व शीतल',
    freshnessDesc: 'जमीन से सीधे सौर मोटर द्वारा निकाला गया ताज़ा पानी।',
    rulesTitle: 'स्वस्थ रहने के 3 आसान नियम (बच्चों व बड़ों के लिए)',
    rule1Title: '1. हरा निशान देखें',
    rule1Desc: 'जब ऊपर हरा बोर्ड दिखे, तभी नल से पानी भरें।',
    rule2Title: '2. साफ़ बर्तन इस्तेमाल करें',
    rule2Desc: 'घर से धोई हुई बोतल या ढक्कनदार बाल्टी लाएं।',
    rule3Title: '3. सीधे पिएं (उबालने की ज़रूरत नहीं)',
    rule3Desc: 'यह पानी सौर फ़िल्टर द्वारा 100% शुद्ध किया गया है।',
    weeklyTitle: 'पिछले 7 दिनों में पानी कैसा रहा?',
    pureLabel: 'शुद्ध',
    impureLabel: 'अशुद्ध',
    loadingHistory: 'इतिहास लोड हो रहा है...',
    caretakerTitle: 'गाँव की जल सहिया (मददगार)',
    caretakerDesc: 'आपके गाँव में जल केंद्र की देख-रेख व सफाई की प्रभारी।',
    callJalSahiya: 'जल सहिया को फ़ोन लगाएं',
    nearestWaterTitle: 'पास के दूसरे सुरक्षित नल (नक्शा)',
    nearestWaterSubtitle: 'आपके प्रखंड के चालू और सुरक्षित जल केंद्र:',
    selectLocationTitle: 'अपना स्थान चुनें (Select Your Location)',
    selectLocationSubtitle: 'अपने जिले या प्रखंड पर क्लिक करें, उस स्थान का लाइव पानी डेटा तुरंत नीचे दिखेगा:',
    autoDetectBtn: '📍 मेरा नजदीकी नल खोजें',
    detecting: 'स्थान खोजा जा रहा है...',
    stationsLabel: 'जल केंद्र',
    speakingAudio: 'बोल रहा है...',
    tdsMetricDesc: 'खनिज संतुलन (BIS मानक ≤ 500)',
    phMetricDesc: 'संतुलित pH (BIS मानक 6.5 – 8.5)',
    turbidityMetricDesc: 'शीशे जैसा साफ़ (BIS मानक ≤ 1.0)',
    tempMetricDesc: 'ताज़ा व शीतल जल (10 - 35°C)'
  },
  kht: {
    portalTitle: 'स्मार्ट पानी सफाई आरु जांच पोर्टल',
    deptTitle: 'पिये के पानी आरु सफई बिभाग • झारखण्ड सरकार',
    sihRef: 'समस्या नंबर: SIH26040 | हार्डवेयर आरु सौर ऊर्जा IoT',
    publicView: 'जनता / गाँव-घरक नजारा',
    phedView: 'पीएचईडी सरकारी दफ्तर',
    liveStream: 'लाईव IoT मशीन चालू हे',
    offlineStream: 'नेटवर्क बन्द / बफ़र मोड',
    safe: 'पिये ले एकदम बेस / सुध पानी',
    unsafe: 'खराब पानी - जिन पिहा',
    offline: 'सिस्टम बन्द हे',
    lastChecked: 'अंतिम जांच समय',
    unitLocation: 'नल / मशीन के जगह',
    parameters: 'पानी जांच के पैमाना (BIS 10500)',
    phLabel: 'pH मान (अमल-खार)',
    tdsLabel: 'पानी में घुलल मिनरल (TDS)',
    turbidityLabel: 'गदलापन / मैलापन',
    tempLabel: 'पानी के गरमाहट',
    safeVerdict: 'पिये खातिर एकदम ठीक',
    unsafeVerdict: 'खतरा सीमा ले बेसी गंदा',
    warningVerdict: 'सावधानी सीमा के भीतरी',
    history7Days: 'पाछू ७ दिन के पानी जांच',
    nearbyUnits: 'तोहर प्रखंड में पासे के बेस पानी केंद्र',
    publicAlerts: 'गाँव-घर खातिर जरूरी सूचना',
    filterHealth: 'फ़िल्टर जाली के हाल',
    cartridgeInstalled: 'फ़िल्टर बैठवेक तारीख',
    lastMaintenance: 'पिछला मरम्मत तारीख',
    recirculationLog: 'अपन-आप रिसाइक्लिंग आरु वाल्व लॉग',
    inletVsOutlet: 'कच्चा पानी बनाम छनला पानी तुलना',
    inlet: 'इनलेट (कच्चा बोरवेल पानी)',
    outlet: 'आउटलेट (सुध छनला पानी)',
    fleetOverview: 'गोटा राज्य के मशीन लिस्ट',
    incidentLog: 'खराबी आरु अलर्ट खाता',
    maintenanceTab: 'मरम्मत टाइम-टेबल',
    analyticsTab: 'जिलावार रिपोर्ट आरु बचत',
    simulatorTab: 'ESP32 मशीन सिम्युलेटर',
    totalUnits: 'कुल लगल मशीन',
    safeUnits: 'बेस पानी मशीन',
    unsafeUnits: 'रोकल / रिसाइकिलिंग मशीन',
    offlineUnits: 'बन्द मशीन',
    purifiedToday: 'आज बाटल गेल सुध पानी',
    targetVolume: 'आजुक लक्ष्य',
    exportCsv: 'रिपोर्ट CSV डाउनलोड करा',
    acknowledge: 'अलर्ट देखल गेल',
    resolve: 'ठीक करि देल गेल',
    logMaintenance: 'मरम्मत दर्ज करा',
    costPerLitre: 'खर्चा प्रति लीटर (RO से सस्ता)',
    waterRecovery: 'पानी बचाव अनुपात',
    co2Saved: 'सौर ऊर्जा से कार्बन बचत',
    login: 'अफसर लॉगिन',
    logout: 'लॉगआउट',
    selectUnit: 'मशीन चुना',
    searchPlaceholder: 'जिला, प्रखंड या गाँव से खोजा...',

    // Super Simple Citizen View Keys (Khortha)
    selectedWaterPoint: 'चुनल गेल पानी मशीन',
    stationCode: 'मशीन कोड',
    safeWaterHero: '१००% बेस आरु सुध पानी',
    unsafeWaterHero: 'सावधान! पानी न पिहा',
    offlineWaterHero: 'मशीन बन्द हे',
    safeHeroSubtitle: 'ई पानी एकदम साफ़, मीठ आरु बेस हे। सबे सोझे पी सकत।',
    unsafeHeroSubtitle: 'मशीन पानी साफ़ करे लागल हे। तनी थमहा।',
    offlineHeroSubtitle: 'मशीन मरम्मत खातिर बन्द हे।',
    listenAudio: '🔊 आवाज़ में सुना',
    howIsWaterTitle: 'पानी केसन हे? (सरल बात में)',
    howIsWaterSubtitle: 'गाँव-घर आरु छौआ-पुता खातिर आसान बात',
    simpleViewBtn: '😊 आसान नजारा',
    detailedViewBtn: '📊 मीटर नंबर',
    clarityTitle: 'साफ़-सफाई',
    clarityBadge: 'एकदम साफ़',
    clarityHeading: 'आईना नियर चमकत साफ़',
    clarityDesc: 'पानी में कौनों धूर-माटी नइखे।',
    tasteTitle: 'स्वाद आरु मिनरल (TDS)',
    tasteBadge: 'मीठ पानी',
    tasteHeading: 'मीठ, पातर आरु बेस',
    tasteDesc: 'देह खातिर जरूरी मिनरल भरल हे।',
    balanceTitle: 'संतुलन (pH)',
    balanceBadge: 'ठीक-ठाक',
    balanceHeading: 'न खट्टा, न तितता - एकदम ठीक',
    balanceDesc: 'पेट आरु हाजमा खातिर सबले बेस।',
    freshnessTitle: 'ताजगी आरु ठंडाई',
    freshnessBadge: 'ताज़ा पानी',
    freshnessHeading: 'पिये लायक शीतल ताज़ा',
    freshnessDesc: 'सौर मोटर से निकलल ताज़ा पानी।',
    rulesTitle: 'पानी पिये के ३ आसान नियम',
    rule1Title: '१. हरियर बोर्ड देखा',
    rule1Desc: 'जब ऊपर हरियर सिग्नल दिखे, तब्बे पानी भरा।',
    rule2Title: '२. साफ़ बर्तन लइहा',
    rule2Desc: 'घर से धोवल बोतल या बाल्टी लइहा।',
    rule3Title: '३. सोझे पिहा (उबालेक जरूरत नइखे)',
    rule3Desc: 'ई पानी सौर फ़िल्टर से १००% सुध हे।',
    weeklyTitle: 'पाछू ७ दिन में पानी केसन रहल?',
    pureLabel: 'सुध',
    impureLabel: 'असुध',
    loadingHistory: 'इतिहास लोड होवे लागल हे...',
    caretakerTitle: 'गाँव के जल सहिया',
    caretakerDesc: 'तोहर गाँव में पानी केंद्र के देखभाल के दीदी।',
    callJalSahiya: 'जल सहिया के फ़ोन लगावा',
    nearestWaterTitle: 'पासे के दूसर बेस नल (नक्शा)',
    nearestWaterSubtitle: 'तोहर प्रखंड में चालू बेस पानी केंद्र:',
    selectLocationTitle: 'अपन जगह चुना (Select Location)',
    selectLocationSubtitle: 'अपन जिला या प्रखंड पर क्लिक करा, उ जगह के लाइव पानी डेटा तुरंते नीचे देखल जेतैक:',
    autoDetectBtn: '📍 हमर पासेक नल खोजा',
    detecting: 'जगह खोजल जा रहल हे...',
    stationsLabel: 'पानी केंद्र',
    speakingAudio: 'बोले लागल हे...',
    tdsMetricDesc: 'जरूरी मिनरल (BIS सीमा ≤ 500)',
    phMetricDesc: 'संतुलित pH (BIS सीमा 6.5 – 8.5)',
    turbidityMetricDesc: 'आईना नियर साफ़ (BIS सीमा ≤ 1.0)',
    tempMetricDesc: 'पिये लायक शीतल ताज़ा (10 - 35°C)'
  },
  nag: {
    portalTitle: 'स्मार्ट पानी सुधाई और नाप-जोख पोर्टल',
    deptTitle: 'पिएक पानी और स्वच्छता विभाग • झारखण्ड सरकार',
    sihRef: 'समस्या: SIH26040 | नवीकरणीय ऊर्जा और हार्डवेयर IoT',
    publicView: 'रैयत / जनता खातिर',
    phedView: 'सरकारी अफसर दफ्तर',
    liveStream: 'लाइव IoT मशीन चालू आहे',
    offlineStream: 'ऑफलाइन / बफ़र चालू',
    safe: 'पिएक ले एकदम सुध / ठीक पानी',
    unsafe: 'खराब पानी - जिन पिउ',
    offline: 'ऑफलाइन - नेटवर्क नखे',
    lastChecked: 'आखरी जांच बेरा',
    unitLocation: 'इकाई केर ठीकाना',
    parameters: 'पानी जांच पैरामीटर (BIS 10500)',
    phLabel: 'pH पैमाना',
    tdsLabel: 'घुलल पदार्थ (TDS)',
    turbidityLabel: 'गदलापन (Turbidity)',
    tempLabel: 'पानी केर तापमान',
    safeVerdict: 'पिएक जोग और सुरक्षित',
    unsafeVerdict: 'सीमा से ढेर गंदा',
    warningVerdict: 'चेतावनी दायरा में',
    history7Days: 'बीतल ७ दिन केर लेखा-जोखा',
    nearbyUnits: 'राउरे प्रखंड में पास केर सुध पानी केंद्र',
    publicAlerts: 'गाँव-देहात खातिर जरूरी सूचना',
    filterHealth: 'फ़िल्टर केर मजबूती',
    cartridgeInstalled: 'फ़िल्टर लगएक तारीख',
    lastMaintenance: 'आखरी मरम्मत दिन',
    recirculationLog: 'स्वचालित पुनर्चक्रण और वाल्व लॉग',
    inletVsOutlet: 'कच्चा पानी बनाम सुध पानी तुलना',
    inlet: 'इनलेट (कच्चा बोरिंग पानी)',
    outlet: 'आउटलेट (सुध पिएक पानी)',
    fleetOverview: 'गोटा राज्य केर इकाई सूची',
    incidentLog: 'घटना और अलर्ट लॉग',
    maintenanceTab: 'रखरखाव कार्यक्रम',
    analyticsTab: 'जिलावार हिसाब और बचत',
    simulatorTab: 'ESP32 सिम्युलेटर टेस्ट',
    totalUnits: 'गोटा इकाई संख्या',
    safeUnits: 'सुध पानी इकाई',
    unsafeUnits: 'खराब / रोकल इकाई',
    offlineUnits: 'ऑफलाइन इकाई',
    purifiedToday: 'आज बाटल सुध पानी',
    targetVolume: 'दैनिक लक्ष्य',
    exportCsv: 'CSV रिपोर्ट डाउनलोड करू',
    acknowledge: 'अलर्ट स्वीकारी',
    resolve: 'समाधान होलक',
    logMaintenance: 'मरम्मत दर्ज करू',
    costPerLitre: 'प्रति लीटर खर्च (RO ले कम)',
    waterRecovery: 'पानी बचत अनुपात',
    co2Saved: 'सौर कार्बन बचत',
    login: 'विभागीय लॉगिन',
    logout: 'लॉगआउट',
    selectUnit: 'इकाई चुनू',
    searchPlaceholder: 'जिला, प्रखंड या गाँव खोजू...',

    // Super Simple Citizen View Keys (Nagpuri)
    selectedWaterPoint: 'चुनल जल केंद्र',
    stationCode: 'इकाई कोड',
    safeWaterHero: '१००% सुध और पिएक जोग पानी',
    unsafeWaterHero: 'सावधान! पानी जिन पिउ',
    offlineWaterHero: 'स्टेशन ऑफलाइन आहे',
    safeHeroSubtitle: 'ई पानी एकदम साफ़, मीठा और बेस आहे। सब सीधे पी सकत।',
    unsafeHeroSubtitle: 'मशीन पानी के साफ़ करेक लागल आहे। तनी थमहा।',
    offlineHeroSubtitle: 'स्टेशन मरम्मत खातिर ऑफलाइन आहे।',
    listenAudio: '🔊 आवाज़ में सुनू',
    howIsWaterTitle: 'पानी केसन आहे? (सरल रूप में)',
    howIsWaterSubtitle: 'छौआ-पुता और घर-परिवार खातिर आसान बात',
    simpleViewBtn: '😊 सरल दृश्य',
    detailedViewBtn: '📊 नाप-जोख',
    clarityTitle: 'साफ़-सफ़ाई',
    clarityBadge: 'एकदम साफ़',
    clarityHeading: 'आईना नियर चमकत साफ़',
    clarityDesc: 'पानी में कौनों मैल या माटी नखे।',
    tasteTitle: 'स्वाद और मिनरल (TDS)',
    tasteBadge: 'मीठा पानी',
    tasteHeading: 'मीठा, हल्का और बढ़िया',
    tasteDesc: 'देह खातिर जरूरी मिनरल भरल आहे।',
    balanceTitle: 'संतुलन (pH)',
    balanceBadge: 'संतुलित',
    balanceHeading: 'न खट्टा, न कड़वा - एकदम ठीक',
    balanceDesc: 'पेट और हाजमा खातिर सबले उत्तम।',
    freshnessTitle: 'ताजगी और ठंडाई',
    freshnessBadge: 'ताज़ा पानी',
    freshnessHeading: 'पिएक जोग शीतल ताज़ा',
    freshnessDesc: 'सौर मोटर से निकलल ताज़ा पानी।',
    rulesTitle: 'पानी पिएक केर ३ आसान नियम',
    rule1Title: '१. हरियर निशान देखू',
    rule1Desc: 'जब ऊपर हरियर सिग्नल दिखे, तब्बे पानी भरू।',
    rule2Title: '२. साफ़ बर्तन लाऊ',
    rule2Desc: 'घर से धोवल बोतल या बाल्टी लाऊ।',
    rule3Title: '३. सीधे पिउ (उबालेक जरूरत नखे)',
    rule3Desc: 'ई पानी सौर फ़िल्टर से १००% सुध आहे।',
    weeklyTitle: 'बीतल ७ दिन में पानी केसन रहलक?',
    pureLabel: 'सुध',
    impureLabel: 'अशुद्ध',
    loadingHistory: 'इतिहास लोड होवत आहे...',
    caretakerTitle: 'गाँव केर जल सहिया',
    caretakerDesc: 'राउरे गाँव में पानी केंद्र केर देख-रेख केर दीदी।',
    callJalSahiya: 'जल सहिया के फ़ोन लगाऊ',
    nearestWaterTitle: 'पास केर दूसर सुध नल (नक्शा)',
    nearestWaterSubtitle: 'राउरे प्रखंड में चालू सुध पानी केंद्र:',
    selectLocationTitle: 'अपन ठीकाना चुनू (Select Location)',
    selectLocationSubtitle: 'अपन जिला या प्रखंड पर क्लिक करू, उ जगह केर लाइव पानी डेटा तुरंत नीचे दिसिक:',
    autoDetectBtn: '📍 मोर पास केर नल खोजू',
    detecting: 'ठीकाना खोजात आहे...',
    stationsLabel: 'जल केंद्र',
    speakingAudio: 'बोलत आहे...',
    tdsMetricDesc: 'जरूरी मिनरल (BIS सीमा ≤ 500)',
    phMetricDesc: 'संतुलित pH (BIS सीमा 6.5 – 8.5)',
    turbidityMetricDesc: 'आईना नियर साफ़ (BIS सीमा ≤ 1.0)',
    tempMetricDesc: 'पिएक जोग शीतल ताज़ा (10 - 35°C)'
  },
  sat: {
    portalTitle: 'ᱥᱢᱟᱨᱴ ᱫᱟᱜ ᱥᱟᱯᱷᱟ ᱟᱨ ᱜᱩᱱ ᱧᱮᱞ-ᱡᱚᱛᱚᱱ ᱯᱳᱨᱴᱟᱞ (Smart Da: Portal)',
    deptTitle: 'ᱧᱩ ᱫᱟᱜ ᱟᱨ ᱥᱟᱯᱷᱟ-ᱥᱟᱯᱷᱤ ᱵᱤᱵᱷᱟᱜᱽ • ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ',
    sihRef: 'SIH26040 | ᱦᱟᱨᱰᱣᱮᱭᱟᱨ ᱟᱨ ᱥᱳᱞᱟᱨ IoT',
    publicView: 'ᱟᱹᱛᱩ-ᱴᱚᱞᱟ / ᱦᱚᱲ ᱧᱮᱞ (Public)',
    phedView: 'ᱥᱚᱨᱠᱟᱨᱤ ᱵᱤᱵᱷᱟᱜᱽ ᱯᱳᱨᱴᱟᱞ (PHED)',
    liveStream: 'ᱞᱟᱭᱤᱵᱽ IoT ᱴᱮᱞᱤᱢᱤᱴᱨᱤ ᱪᱟᱹᱞᱩ',
    offlineStream: 'ᱚᱯᱷᱞᱟᱭᱤᱱ / ᱵᱟᱯᱷᱟᱨ',
    safe: 'ᱧᱩ ᱞᱟᱹᱜᱤᱫ ᱵᱮᱥ / ᱥᱟᱯᱷᱟ ᱫᱟᱜ (SAFE)',
    unsafe: 'ᱵᱟᱹᱲᱤᱡ ᱫᱟᱜ - ᱟᱞᱚᱯᱮ ᱧᱩᱭᱟ (UNSAFE)',
    offline: 'ᱚᱯᱷᱞᱟᱭᱤᱱ (OFFLINE)',
    lastChecked: 'ᱢᱩᱪᱟᱹᱫ ᱡᱟᱸᱪ ᱚᱠᱛᱚ',
    unitLocation: 'ᱫᱟᱜ ᱴᱷᱟᱶ',
    parameters: 'ᱫᱟᱜ ᱜᱩᱱ ᱯᱟᱹᱭᱢᱟᱱᱟ (BIS 10500)',
    phLabel: 'pH ᱢᱟᱱ',
    tdsLabel: 'ᱦᱟᱥᱟ-ᱢᱤᱱᱨᱟᱞ ᱢᱮᱥᱟ (TDS)',
    turbidityLabel: 'ᱵᱚᱦᱮᱞ ᱜᱟᱫᱽᱞᱟ (Turbidity)',
    tempLabel: 'ᱫᱟᱜ ᱞᱚᱞᱚ-ᱨᱮᱭᱟᱲ',
    safeVerdict: 'ᱧᱩ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱯᱷᱟ ᱜᱮᱭᱟ',
    unsafeVerdict: 'ᱢᱟᱱᱚᱠ ᱠᱷᱚᱱ ᱵᱟᱹᱲᱛᱤ ᱢᱮᱱᱟᱜ-ᱟ',
    warningVerdict: 'ᱦᱩᱥᱤᱭᱟᱹᱨ ᱥᱤᱢᱟᱹ ᱨᱮ',
    history7Days: 'ᱯᱟᱨᱚᱢᱮᱱ ᱗ ᱢᱟᱦᱟᱸ ᱨᱮᱱᱟᱜ ᱫᱟᱜ ᱦᱟᱞᱚᱛ',
    nearbyUnits: 'ᱥᱩᱨ ᱨᱮᱱᱟᱜ ᱵᱮᱥ ᱫᱟᱜ ᱴᱷᱟᱶ',
    publicAlerts: 'ᱦᱚᱲ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱠᱷᱚᱵᱚᱨ',
    filterHealth: 'ᱯᱷᱤᱞᱴᱟᱨ ᱦᱟᱞᱚᱛ',
    cartridgeInstalled: 'ᱯᱷᱤᱞᱴᱟᱨ ᱵᱟᱹᱭᱥᱟᱹᱣ ᱢᱟᱦᱟᱸ',
    lastMaintenance: 'ᱢᱩᱪᱟᱹᱫ ᱢᱮᱨᱟᱢᱚᱛ ᱢᱟᱦᱟᱸ',
    recirculationLog: 'ᱟᱡᱛᱮ ᱫᱟᱜ ᱥᱟᱯᱷᱟ ᱟᱨ ᱵᱷᱟᱞᱵᱽ ᱞᱚᱜᱽ',
    inletVsOutlet: 'ᱵᱮᱨᱮᱞ ᱫᱟᱜ ᱟᱨ ᱥᱟᱯᱷᱟ ᱫᱟᱜ ᱛᱩᱞᱟᱹᱡᱚᱠᱷᱟ',
    inlet: 'ᱵᱮᱨᱮᱞ ᱫᱟᱜ (Inlet)',
    outlet: 'ᱥᱟᱯᱷᱟ ᱫᱟᱜ (Outlet)',
    fleetOverview: 'ᱡᱚᱛᱚ ᱫᱟᱜ ᱢᱤᱥᱤᱱ ᱛᱟᱹᱞᱠᱟᱹ',
    incidentLog: 'ᱮᱴᱠᱮᱴᱚᱬᱮ ᱟᱨ ᱟᱞᱟᱨᱴ ᱞᱚᱜᱽ',
    maintenanceTab: 'ᱢᱮᱨᱟᱢᱚᱛ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ',
    analyticsTab: 'ᱡᱤᱞᱟᱹ ᱦᱤᱥᱟᱹᱵᱽ ᱟᱨ ᱵᱟᱧᱪᱟᱣ',
    simulatorTab: 'ESP32 ᱥᱤᱢᱩᱞᱮᱴᱟᱨ',
    totalUnits: 'ᱡᱚᱛᱚ ᱢᱤᱥᱤᱱ',
    safeUnits: 'ᱵᱮᱥ ᱫᱟᱜ ᱢᱤᱥᱤᱱ',
    unsafeUnits: 'ᱟᱴᱠᱟᱣ ᱢᱤᱥᱤᱱ',
    offlineUnits: 'ᱚᱯᱷᱞᱟᱭᱤᱱ ᱢᱤᱥᱤᱱ',
    purifiedToday: 'ᱛᱮᱦᱮᱧ ᱦᱟᱹᱴᱤᱧ ᱥᱟᱯᱷᱟ ᱫᱟᱜ',
    targetVolume: 'ᱫᱤᱱᱟᱹᱢ ᱴᱟᱨᱜᱮᱴ',
    exportCsv: 'CSV ᱨᱤᱯᱳᱨᱴ ᱰᱟᱣᱩᱱᱞᱳᱰ',
    acknowledge: 'ᱟᱞᱟᱨᱴ ᱧᱮᱞᱮᱱᱟ',
    resolve: 'ᱵᱮᱥ ᱮᱱᱟ',
    logMaintenance: 'ᱢᱮᱨᱟᱢᱚᱛ ᱚᱞ ᱢᱮ',
    costPerLitre: 'ᱞᱤᱴᱟᱨ ᱯᱤᱪᱷᱤ ᱠᱷᱚᱨᱚᱪ (RO ᱠᱷᱚᱱ ᱠᱚᱢ)',
    waterRecovery: 'ᱫᱟᱜ ᱵᱟᱧᱪᱟᱣ ᱦᱤᱥᱟᱹᱵᱽ',
    co2Saved: 'ᱥᱳᱞᱟᱨ ᱠᱟᱨᱵᱚᱱ ᱵᱟᱧᱪᱟᱣ',
    login: 'ᱞᱚᱜᱤᱱ',
    logout: 'ᱞᱚᱜᱽ ᱟᱣᱩᱴ',
    selectUnit: 'ᱢᱤᱥᱤᱱ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    searchPlaceholder: 'ᱡᱤᱞᱟᱹ, ᱵᱞᱚᱠ ᱥᱮ ᱟᱹᱛᱩ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...',

    // Super Simple Citizen View Keys (Santali)
    selectedWaterPoint: 'ᱵᱟᱪᱷᱟᱣ ᱫᱟᱜ ᱴᱷᱟᱶ',
    stationCode: 'ᱢᱤᱥᱤᱱ ᱠᱳᱰ',
    safeWaterHero: '᱑᱐᱐% ᱥᱟᱯᱷᱟ ᱟᱨ ᱧᱩ ᱫᱟᱜ',
    unsafeWaterHero: 'ᱦᱩᱥᱤᱭᱟᱹᱨ! ᱫᱟᱜ ᱟᱞᱚᱯᱮ ᱧᱩᱭᱟ',
    offlineWaterHero: 'ᱚᱯᱷᱞᱟᱭᱤᱱ ᱢᱮᱱᱟᱜ-ᱟ',
    safeHeroSubtitle: 'ᱱᱚᱣᱟ ᱫᱟᱜ ᱫᱚ ᱟᱹᱰᱤ ᱥᱟᱯᱷᱟ ᱟᱨ ᱦᱮᱲᱮᱢ ᱜᱮᱭᱟ। ᱡᱚᱛᱚ ᱦᱚᱲ ᱧᱩ ᱫᱟᱲᱮᱭᱟᱜ-ᱟ।',
    unsafeHeroSubtitle: 'ᱢᱤᱥᱤᱱ ᱫᱟᱜ ᱥᱟᱯᱷᱟ ᱮᱫᱟᱭ। ᱛᱷᱚᱲᱟ ᱛᱟᱺᱜᱤ ᱢᱮ।',
    offlineHeroSubtitle: 'ᱢᱮᱨᱟᱢᱚᱛ ᱠᱷᱟᱹᱛᱤᱨ ᱚᱯᱷᱞᱟᱭᱤᱱ ᱢᱮᱱᱟᱜ-ᱟ।',
    listenAudio: '🔊 ᱟᱲᱟᱝ ᱛᱮ ᱟᱧᱡᱚᱢ ᱢᱮ',
    howIsWaterTitle: 'ᱫᱟᱜ ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱜ-ᱟ?',
    howIsWaterSubtitle: 'ᱜᱤᱫᱽᱨᱟᱹ ᱟᱨ ᱚᱲᱟᱜ ᱦᱚᱲ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱯᱷᱟ ᱠᱟᱛᱷᱟ',
    simpleViewBtn: '😊 ᱟᱞᱜᱟ ᱧᱮᱞ',
    detailedViewBtn: '📊 ᱢᱤᱴᱟᱨ ᱦᱤᱥᱟᱹᱵᱽ',
    clarityTitle: 'ᱥᱟᱯᱷᱟ-ᱥᱟᱹᱯᱷᱤ',
    clarityBadge: 'ᱥᱟᱯᱷᱟ ᱜᱮᱭᱟ',
    clarityHeading: 'ᱟᱹᱨᱥᱤ ᱞᱮᱠᱟ ᱥᱟᱯᱷᱟ',
    clarityDesc: 'ᱫᱟᱜ ᱨᱮ ᱪᱮᱫ ᱦᱟᱥᱟ ᱦᱚᱸ ᱵᱟᱹᱱᱩᱜ-ᱟ।',
    tasteTitle: 'ᱦᱮᱲᱮᱢ ᱟᱨ ᱢᱤᱱᱨᱟᱞ (TDS)',
    tasteBadge: 'ᱦᱮᱲᱮᱢ ᱫᱟᱜ',
    tasteHeading: 'ᱦᱮᱲᱮᱢ ᱟᱨ ᱵᱮᱥ',
    tasteDesc: 'ᱦᱚᱲᱢᱚ ᱞᱟᱹᱜᱤᱫ ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱢᱤᱱᱨᱟᱞ ᱢᱮᱱᱟᱜ-ᱟ।',
    balanceTitle: 'ᱥᱚᱢᱟᱱ ᱜᱩᱱ (pH)',
    balanceBadge: 'ᱥᱚᱢᱟᱱ ᱜᱮᱭᱟ',
    balanceHeading: 'ᱵᱟᱝ ᱡᱚᱡᱚ, ᱵᱟᱝ ᱦᱟᱫᱽ - ᱵᱮᱥ ᱜᱮᱭᱟ',
    balanceDesc: 'ᱞᱟᱡ ᱟᱨ ᱡᱚᱢ ᱦᱟᱡᱚᱢ ᱞᱟᱹᱜᱤᱫ ᱟᱹᱰᱤ ᱵᱮᱥ।',
    freshnessTitle: 'ᱞᱚᱞᱚ-ᱨᱮᱭᱟᱲ ᱦᱟᱞᱚᱛ',
    freshnessBadge: 'ᱨᱮᱭᱟᱲ ᱫᱟᱜ',
    freshnessHeading: 'ᱧᱩ ᱞᱮᱠᱟ ᱨᱮᱭᱟᱲ ᱛᱟᱡᱟ',
    freshnessDesc: 'ᱥᱳᱞᱟᱨ ᱢᱳᱴᱚᱨ ᱛᱮ ᱚᱰᱚᱠ ᱛᱟᱡᱟ ᱫᱟᱜ।',
    rulesTitle: 'ᱫᱟᱜ ᱧᱩ ᱨᱮᱱᱟᱜ ᱓ ᱟᱞᱜᱟ ᱱᱤᱭᱚᱢ',
    rule1Title: '᱑. ᱦᱟᱹᱨᱭᱟᱹᱲ ᱵᱳᱨᱰ ᱧᱮᱞ ᱢᱮ',
    rule1Desc: 'ᱪᱮᱛᱟᱱ ᱨᱮ ᱦᱟᱹᱨᱭᱟᱹᱲ ᱪᱤᱱᱦᱟᱹ ᱛᱟᱦᱮᱱ ᱠᱷᱟᱱ ᱫᱟᱜ ᱞᱩᱭ ᱢᱮ।',
    rule2Title: '᱒. ᱥᱟᱯᱷᱟ ᱵᱟᱹᱴᱤ/ᱵᱚᱛᱚᱞ ᱟᱹᱜᱩᱭ ᱢᱮ',
    rule2Desc: 'ᱚᱲᱟᱜ ᱠᱷᱚᱱ ᱥᱟᱯᱷᱟ ᱵᱚᱛᱚᱞ ᱥᱮ ᱵᱟᱹᱞᱛᱤ ᱟᱹᱜᱩᱭ ᱢᱮ।',
    rule3Title: '᱓. ᱥᱚᱡᱷᱮ ᱧᱩᱭ ᱢᱮ (ᱦᱮᱰᱮᱡ ᱵᱟᱝ ᱞᱟᱹᱠᱛᱤᱭᱟ)',
    rule3Desc: 'ᱱᱚᱣᱟ ᱫᱟᱜ ᱫᱚ ᱥᱳᱞᱟᱨ ᱯᱷᱤᱞᱴᱟᱨ ᱛᱮ ᱑᱐᱐% ᱥᱟᱯᱷᱟ ᱜᱮᱭᱟ।',
    weeklyTitle: 'ᱯᱟᱨᱚᱢᱮᱱ ᱗ ᱢᱟᱦᱟᱸ ᱨᱮ ᱫᱟᱜ ᱪᱮᱫ ᱞᱮᱠᱟ ᱛᱟᱦᱮᱸ ᱠᱟᱱᱟ?',
    pureLabel: 'ᱥᱟᱯᱷᱟ',
    impureLabel: 'ᱵᱟᱹᱲᱤᱡ',
    loadingHistory: 'ᱦᱤᱥᱟᱹᱵᱽ ᱞᱳᱰᱚᱜ ᱠᱟᱱᱟ...',
    caretakerTitle: 'ᱟᱹᱛᱩ ᱨᱤᱱᱤᱡ ᱡᱚᱞ ᱥᱟᱦᱤᱭᱟ',
    caretakerDesc: 'ᱟᱹᱛᱩ ᱨᱮ ᱫᱟᱜ ᱴᱷᱟᱶ ᱧᱮᱞ-ᱡᱚᱛᱚᱱ ᱟᱹᱭᱫᱟᱹᱨᱤᱭᱟᱹ।',
    callJalSahiya: 'ᱡᱚᱞ ᱥᱟᱦᱤᱭᱟ ᱯᱷᱳᱱ ᱮᱢᱟᱭ ᱢᱮ',
    nearestWaterTitle: 'ᱥᱩᱨ ᱨᱮᱱᱟᱜ ᱮᱴᱟᱜ ᱵᱮᱥ ᱫᱟᱜ ᱴᱷᱟᱶ (ᱢᱮᱯ)',
    nearestWaterSubtitle: 'ᱵᱞᱚᱠ ᱨᱮᱱᱟᱜ ᱪᱟᱹᱞᱩ ᱥᱟᱯᱷᱟ ᱫᱟᱜ ᱴᱷᱟᱶ:',
    selectLocationTitle: 'ᱟᱯᱱᱟᱨ ᱴᱷᱟᱶ ᱵᱟᱪᱷᱟᱣ ᱢᱮ (Select Location)',
    selectLocationSubtitle: 'ᱟᱯᱱᱟᱨ ᱡᱤᱞᱟᱹ ᱥᱮ ᱵᱞᱚᱠ ᱨᱮ ᱚᱛᱟᱭ ᱢᱮ, ᱚᱱᱟ ᱴᱷᱟᱶ ᱨᱮᱱᱟᱜ ᱞᱟᱭᱤᱵᱽ ᱫᱟᱜ ᱰᱮᱴᱟ ᱞᱟᱛᱟᱨ ᱨᱮ ᱧᱮᱞᱚᱜ-ᱟ:',
    autoDetectBtn: '📍 ᱥᱩᱨ ᱨᱮᱱᱟᱜ ᱫᱟᱜ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ',
    detecting: 'ᱴᱷᱟᱶ ᱥᱮᱸᱫᱽᱨᱟᱜ ᱠᱟᱱᱟ...',
    stationsLabel: 'ᱫᱟᱜ ᱴᱷᱟᱶ',
    speakingAudio: 'ᱨᱚᱲ ᱠᱟᱱᱟᱭ...',
    tdsMetricDesc: 'ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱢᱤᱱᱨᱟᱞ (BIS ≤ 500)',
    phMetricDesc: 'ᱥᱚᱢᱟᱱ pH (BIS 6.5 – 8.5)',
    turbidityMetricDesc: 'ᱟᱹᱨᱥᱤ ᱞᱮᱠᱟ ᱥᱟᱯᱷᱟ (BIS ≤ 1.0)',
    tempMetricDesc: 'ᱧᱩ ᱞᱮᱠᱟ ᱨᱮᱭᱟᱲ ᱛᱟᱡᱟ (10 - 35°C)'
  },
  bn: {
    portalTitle: 'স্মার্ট জল বিশুদ্ধকরণ ও গুণমান পর্যবেক্ষণ পোর্টাল',
    deptTitle: 'পানীয় জল ও স্যানিটেশন বিভাগ • ঝাড়খণ্ড সরকার',
    sihRef: 'সমস্যা কোড: SIH26040 | টেকসই শক্তি ও হার্ডওয়্যার IoT',
    publicView: 'নাগরিক / সাধারণ দৃশ্য',
    phedView: 'পিএইচইডি বিভাগীয় পোর্টাল',
    liveStream: 'লাইভ IoT টেলিমেট্রি সক্রিয়',
    offlineStream: 'অফলাইন / বাফার মোড',
    safe: 'পান করার জন্য নিরাপদ',
    unsafe: 'অনিরাপদ - পান করবেন না',
    offline: 'অফলাইন',
    lastChecked: 'সর্বশেষ যাচাইয়ের সময়',
    unitLocation: 'ইউনিটের অবস্থান',
    parameters: 'জল গুণমান প্যারামিটার (BIS 10500 মানদণ্ড)',
    phLabel: 'pH ভারসাম্য (অম্লতা/ক্ষারকতা)',
    tdsLabel: 'মোট দ্রবীভূত কঠিন পদার্থ (TDS)',
    turbidityLabel: 'ঘোলাটে ভাব (Turbidity)',
    tempLabel: 'জলের তাপমাত্রা',
    safeVerdict: 'পানযোগ্য এবং নিরাপদ',
    unsafeVerdict: 'অনুমোদিত সীমার বাইরে',
    warningVerdict: 'সতর্কতা সীমার কাছাকাছি',
    history7Days: 'বিগত ৭ দিনের জল গুণমান ইতিহাস',
    nearbyUnits: 'আপনার ব্লকে কাছাকাছি নিরাপদ জলের পয়েন্ট',
    publicAlerts: 'জনস্বাস্থ্য পরামর্শ ও সতর্কতা',
    filterHealth: 'ফিল্টার কার্টিজের অবস্থা',
    cartridgeInstalled: 'কার্টিজ স্থাপনের তারিখ',
    lastMaintenance: 'সর্বশেষ রক্ষণাবেক্ষণের তারিখ',
    recirculationLog: 'স্বয়ংক্রিয় পুনর্সঞ্চালন ও সলিনয়েড ভালভ লগ',
    inletVsOutlet: 'অপরিশোধিত জল বনাম বিশুদ্ধ জলের তুলনা',
    inlet: 'ইনলেট (অপরিশোধিত জল)',
    outlet: 'আউটলেট (বিশুদ্ধ জল)',
    fleetOverview: 'রাজ্যব্যাপী ইউনিট সমীক্ষা',
    incidentLog: 'ঘটনা ও সতর্কতা লগ',
    maintenanceTab: 'রক্ষণাবেক্ষণ সূচি',
    analyticsTab: 'জেলা ভিত্তিক বিশ্লেষণ ও সাশ্রয়',
    simulatorTab: 'ESP32 সিমুলেটর ও সিঙ্ক',
    totalUnits: 'মোট নিরীক্ষণ ইউনিট',
    safeUnits: 'নিরাপদ ইউনিট',
    unsafeUnits: 'অনিরাপদ / পুনর্সঞ্চালিত',
    offlineUnits: 'অফলাইন ইউনিট',
    purifiedToday: 'আজ সরবরাহকৃত বিশুদ্ধ জল',
    targetVolume: 'দৈনিক লক্ষ্যমাত্রা',
    exportCsv: 'CSV রিপোর্ট ডাউনলোড করুন',
    acknowledge: 'সতর্কতা স্বীকার করুন',
    resolve: 'সমাধান হিসেবে চিহ্নিত করুন',
    logMaintenance: 'রক্ষণাবেক্ষণ নথিবদ্ধ করুন',
    costPerLitre: 'প্রতি লিটার খরচ (RO-এর চেয়ে কম)',
    waterRecovery: 'জল পুনরুদ্ধার অনুপাত',
    co2Saved: 'সৌর কার্বন সাশ্রয়',
    login: 'অফিসিয়াল লগইন',
    logout: 'লগআউট',
    selectUnit: 'ইউনিট নির্বাচন করুন',
    searchPlaceholder: 'জেলা, ব্লক, পঞ্চায়েত বা ইউনিট আইডি দিয়ে খুঁজুন...',

    // Super Simple Citizen View Keys (Bengali)
    selectedWaterPoint: 'নির্বাচিত জল কেন্দ্র',
    stationCode: 'স্টেশন কোড',
    safeWaterHero: '১০০% বিশুদ্ধ এবং নিরাপদ পানীয় জল',
    unsafeWaterHero: 'সতর্কতা! এই জল পান করবেন না',
    offlineWaterHero: 'স্টেশনটি বর্তমানে অফলাইনে রয়েছে',
    safeHeroSubtitle: 'এই জল সম্পূর্ণ পরিষ্কার, মিষ্টি এবং স্বাস্থ্যকর। সবাই সরাসরি পান করতে পারেন।',
    unsafeHeroSubtitle: 'ফিল্টার জল থেকে ময়লা পরিষ্কার করছে। অনুগ্রহ করে কিছুক্ষণ অপেক্ষা করুন।',
    offlineHeroSubtitle: 'রক্ষণাবেক্ষণের জন্য স্টেশন টেলিমেট্রি অফলাইনে রয়েছে।',
    listenAudio: '🔊 ভয়েস শুনুন (Listen)',
    howIsWaterTitle: 'জল এখন কেমন আছে? (সহজ ভাষায়)',
    howIsWaterSubtitle: 'বাচ্চা ও পরিবারের জন্য সহজ ৪টি সূচক',
    simpleViewBtn: '😊 সহজ দৃশ্য',
    detailedViewBtn: '📊 সঠিক মিটার',
    clarityTitle: 'পরিষ্কার-পরিচ্ছন্নতা',
    clarityBadge: 'সম্পূর্ণ পরিষ্কার',
    clarityHeading: 'কাঁচের মতো স্বচ্ছ ও পরিষ্কার',
    clarityDesc: 'জলে কোনো ধুলো, কাদা বা ময়লা নেই।',
    tasteTitle: 'স্বাদ ও খনিজ (TDS)',
    tasteBadge: 'মিষ্টি জল',
    tasteHeading: 'মিষ্টি, হালকা ও স্বাস্থ্যকর',
    tasteDesc: 'শরীরের জন্য প্রয়োজনীয় খনিজ সমৃদ্ধ।',
    balanceTitle: 'প্রাকৃতিক ভারসাম্য (pH)',
    balanceBadge: 'ভারসাম্যপূর্ণ',
    balanceHeading: 'টক নয়, তেতো নয় - একদম নিখুঁত',
    balanceDesc: 'পেট ও হজমের জন্য সবচেয়ে উপযুক্ত pH মান।',
    freshnessTitle: 'তাজা ভাব ও তাপমাত্রা',
    freshnessBadge: 'তাজা ও শীতল',
    freshnessHeading: 'পানযোগ্য তাজা ও ঠাণ্ডা জল',
    freshnessDesc: 'সৌর পাম্প দিয়ে মাটি থেকে তোলা তাজা জল।',
    rulesTitle: 'সুস্থ থাকার ৩টি সহজ নিয়ম',
    rule1Title: '১. সবুজ চিহ্ন দেখুন',
    rule1Desc: 'উপরে সবুজ SAFE বোর্ড দেখলে তবেই জল ভরুন।',
    rule2Title: '২. পরিষ্কার পাত্র আনুন',
    rule2Desc: 'বাড়ি থেকে ধোয়া বোতল বা ঢাকনাযুক্ত পাত্র আনুন।',
    rule3Title: '৩. সরাসরি পান করুন (ফোটানোর দরকার নেই)',
    rule3Desc: 'এই জল সৌর ফিল্টার দ্বারা ১০০% বিশুদ্ধ।',
    weeklyTitle: 'বিগত ৭ দিনে জলের অবস্থা কেমন ছিল?',
    pureLabel: 'বিশুদ্ধ',
    impureLabel: 'অবিশুদ্ধ',
    loadingHistory: 'ইতিহাস লোড হচ্ছে...',
    caretakerTitle: 'গ্রামের জল সহিয়া',
    caretakerDesc: 'আপনার গ্রামে জল কেন্দ্রের দেখাশোনার দায়িত্বপ্রাপ্ত।',
    callJalSahiya: 'জল সহিয়াকে ফোন করুন',
    nearestWaterTitle: 'কাছাকাছি অন্য নিরাপদ জলের কল (ম্যাপ)',
    nearestWaterSubtitle: 'আপনার ব্লকের চালু ও নিরাপদ জল কেন্দ্র:',
    selectLocationTitle: 'আপনার স্থান নির্বাচন করুন (Select Location)',
    selectLocationSubtitle: 'আপনার জেলা বা ব্লকে ক্লিক করুন, সেই স্থানের রিয়েল-টাইম জলের তথ্য নিচে দেখতে পাবেন:',
    autoDetectBtn: '📍 নিকটবর্তী জলের কল খুঁজুন',
    detecting: 'অবস্থান খোঁজা হচ্ছে...',
    stationsLabel: 'জল কেন্দ্র',
    speakingAudio: 'বলছে...',
    tdsMetricDesc: 'প্রয়োজনীয় খনিজ (BIS মানদণ্ড ≤ 500)',
    phMetricDesc: 'ভারসাম্যপূর্ণ pH (BIS 6.5 – 8.5)',
    turbidityMetricDesc: 'কাঁচের মতো স্বচ্ছ (BIS মানদণ্ড ≤ 1.0)',
    tempMetricDesc: 'পানযোগ্য তাজা ও ঠাণ্ডা জল (10 - 35°C)'
  },
  mun: {
    portalTitle: 'स्मार्ट दाः साफा आर जांच पोर्टल',
    deptTitle: 'नु दाः आर सफई विभाग • झारखण्ड सरकार',
    sihRef: 'समस्या: SIH26040 | हार्डवेयर आर सोलर IoT',
    publicView: 'हातु-टोला / होड़ो को ल़ागित्',
    phedView: 'सरकारी दफ्तर पोर्टल',
    liveStream: 'लाइव IoT टेलीमेट्री चालू',
    offlineStream: 'ऑफलाइन / बफ़र मोड',
    safe: 'नु ल़ागित् बेस / साफा दाः',
    unsafe: 'का बेस दाः - आलोपे नुया',
    offline: 'ऑफलाइन',
    lastChecked: 'टुंगु जांच ओकोतो',
    unitLocation: 'दाः ठिकाना',
    parameters: 'दाः गुण पैमाना (BIS 10500)',
    phLabel: 'pH मान',
    tdsLabel: 'घुलल मिनरल (TDS)',
    turbidityLabel: 'गदला दाः (Turbidity)',
    tempLabel: 'दाः तापमान',
    safeVerdict: 'नु ल़ागित् बेस गेया',
    unsafeVerdict: 'खतरा सीमा ते का बेस',
    warningVerdict: 'सावधानी दायरा रे',
    history7Days: 'बीतल ७ दिन रियाः दाः हाल',
    nearbyUnits: 'नेपाः रेयाः बेस दाः केंद्र',
    publicAlerts: 'हातु को ल़ागित् सूचना',
    filterHealth: 'फ़िल्टर हाल',
    cartridgeInstalled: 'फ़िल्टर लगावे दिन',
    lastMaintenance: 'टुंगु मरम्मत दिन',
    recirculationLog: 'अपन-आप रिसाइक्लिंग लॉग',
    inletVsOutlet: 'कच्चा दाः बनाम साफा दाः',
    inlet: 'कच्चा दाः (Inlet)',
    outlet: 'साफा दाः (Outlet)',
    fleetOverview: 'गोटा राज्य इकाई लिस्ट',
    incidentLog: 'घटना आर अलर्ट खाता',
    maintenanceTab: 'मरम्मत काम-काज',
    analyticsTab: 'जिलावार हिसाब आर बचत',
    simulatorTab: 'ESP32 सिम्युलेटर',
    totalUnits: 'कुल इकाई',
    safeUnits: 'बेस दाः इकाई',
    unsafeUnits: 'का बेस इकाई',
    offlineUnits: 'ऑफलाइन इकाई',
    purifiedToday: 'तिहिंग बाटल साफा दाः',
    targetVolume: 'दैनिक टारगेट',
    exportCsv: 'CSV रिपोर्ट डाउनलोड',
    acknowledge: 'अलर्ट नेलेना',
    resolve: 'बेस हेना',
    logMaintenance: 'मरम्मत ओलेमे',
    costPerLitre: 'प्रति लीटर खर्च (RO ले कम)',
    waterRecovery: 'दाः बचाव हिसाब',
    co2Saved: 'सोलर कार्बन बचत',
    login: 'लॉगइन',
    logout: 'लॉगआउट',
    selectUnit: 'इकाई बाछामे',
    searchPlaceholder: 'जिला, प्रखंड बा हातु खोजेमे...',

    // Super Simple Citizen View Keys (Mundari)
    selectedWaterPoint: 'बाछल दाः केंद्र',
    stationCode: 'इकाई कोड',
    safeWaterHero: '१००% साफा आर नु ल़ागित् बेस दाः',
    unsafeWaterHero: 'सावधान! दाः आलोपे नुया',
    offlineWaterHero: 'स्टेशन ऑफलाइन मेनाः',
    safeHeroSubtitle: 'ने दाः अडी बेस आर हेड़ेम गेया। सबे नु दाड़ेया।',
    unsafeHeroSubtitle: 'मशीन दाः साफा ताना। तनी तांगी मे।',
    offlineHeroSubtitle: 'मरम्मत लागीत् स्टेशन ऑफलाइन मेनाः।',
    listenAudio: '🔊 आवाज़ ते आयुम मे',
    howIsWaterTitle: 'दाः चिलका मेनाः? (सरल कजी)',
    howIsWaterSubtitle: 'छौआ को आर हातु होड़ो ल़ागित् आसान कजी',
    simpleViewBtn: '😊 आसान दृश्य',
    detailedViewBtn: '📊 मीटर नंबर',
    clarityTitle: 'साफ़-सफाई',
    clarityBadge: 'एकदम साफ़',
    clarityHeading: 'आईना लेका साफा',
    clarityDesc: 'दाः रे हसा-धूरी बानोःआ।',
    tasteTitle: 'हेड़ेम आर मिनरल (TDS)',
    tasteBadge: 'हेड़ेम दाः',
    tasteHeading: 'हेड़ेम आर बेस दाः',
    tasteDesc: 'होड़मो ल़ागित् दरकारी मिनरल मेनाः।',
    balanceTitle: 'संतुलन (pH)',
    balanceBadge: 'संतुलित',
    balanceHeading: 'का जोजो, का तितता - बेस गेया',
    balanceDesc: 'लाज आर हाजमा ल़ागित् अडी बेस।',
    freshnessTitle: 'ताजगी आर रयाड़',
    freshnessBadge: 'ताज़ा दाः',
    freshnessHeading: 'नु लेका रयाड़ ताज़ा',
    freshnessDesc: 'सोलर मोटर ते ओडोल ताज़ा दाः।',
    rulesTitle: 'दाः नु रियाः ३ आसान नियम',
    rule1Title: '१. हरियर बोर्ड नेलेमे',
    rule1Desc: 'चेतान रे हरियर सिग्नल नेलोः रे दाः लुमे।',
    rule2Title: '२. साफ़ बर्तन अगुइमे',
    rule2Desc: 'ओड़ाः ते धोवल बोतल बा बाल्टी अगुइमे।',
    rule3Title: '३. सोझे नुइमे (हेडे़ज का दरकार)',
    rule3Desc: 'ने दाः सोलर फ़िल्टर ते १००% साफा गेया।',
    weeklyTitle: 'बीतल ७ दिन रे दाः चिलका ताइकेना?',
    pureLabel: 'साफा',
    impureLabel: 'का साफा',
    loadingHistory: 'इतिहास लोड होवतना...',
    caretakerTitle: 'हातु रियाः जल सहिया',
    caretakerDesc: 'हातु रे दाः केंद्र नेल-जतन दीदी।',
    callJalSahiya: 'जल सहिया के फ़ोन लगावेमे',
    nearestWaterTitle: 'नेपाः रियाः बेस दाः केंद्र (नक्शा)',
    nearestWaterSubtitle: 'प्रखंड रियाः चालू बेस दाः केंद्र:',
    selectLocationTitle: 'अपन जायगा बाछामे (Select Location)',
    selectLocationSubtitle: 'अपन जिला बा प्रखंड रे क्लिक एमे, ने जायगा रियाः लाइव दाः डेटा तुरंत नेलोःआ:',
    autoDetectBtn: '📍 नेपाः रेयाः दाः केंद्र खोजेमे',
    detecting: 'जायगा खोजोः ताना...',
    stationsLabel: 'दाः केंद्र',
    speakingAudio: 'कजी ताना...',
    tdsMetricDesc: 'दरकारी मिनरल (BIS सीमा ≤ 500)',
    phMetricDesc: 'संतुलित pH (BIS 6.5 – 8.5)',
    turbidityMetricDesc: 'आईना लेका साफा (BIS सीमा ≤ 1.0)',
    tempMetricDesc: 'नु लेका रयाड़ ताज़ा (10 - 35°C)'
  },
  ho: {
    portalTitle: 'स्मार्ट दाः साफा आर गुन जांच पोर्टल (Ho)',
    deptTitle: 'नु दाः आर सफई विभाग • झारखण्ड सरकार',
    sihRef: 'समस्या: SIH26040 | हार्डवेयर आर सोलर IoT',
    publicView: 'हातु दिसुम / नागरिक दृश्य',
    phedView: 'सरकारी दफ्तर पोर्टल',
    liveStream: 'लाइव IoT टेलीमेट्री चालू मेनाः',
    offlineStream: 'ऑफलाइन मोड',
    safe: 'नु लेका बेस / साफा दाः (SAFE)',
    unsafe: 'का बेस दाः - का नुएय (UNSAFE)',
    offline: 'ऑफलाइन',
    lastChecked: 'अंतिम जांच समय',
    unitLocation: 'दाः जायगा',
    parameters: 'दाः जांच पैमाना (BIS 10500)',
    phLabel: 'pH मान',
    tdsLabel: 'घुलल मिनरल (TDS)',
    turbidityLabel: 'गदलापन (Turbidity)',
    tempLabel: 'दाः तापमान',
    safeVerdict: 'नु लेका बेस मेंनाः',
    unsafeVerdict: 'खतरा सीमा ले बेसी',
    warningVerdict: 'सावधानी सीमा रे',
    history7Days: 'पाछू ७ दिन रियाः हिसाब',
    nearbyUnits: 'लागातार सुर रेयाः बेस दाः केंद्र',
    publicAlerts: 'हातु दिसुम सूचना',
    filterHealth: 'फ़िल्टर स्थिति',
    cartridgeInstalled: 'फ़िल्टर लगावे दिन',
    lastMaintenance: 'आखरी मरम्मत दिन',
    recirculationLog: 'स्वचालित पुनर्चक्रण लॉग',
    inletVsOutlet: 'कच्चा दाः आर साफा दाः तुलना',
    inlet: 'कच्चा दाः (Inlet)',
    outlet: 'साफा दाः (Outlet)',
    fleetOverview: 'गोटा राज्य इकाई सूची',
    incidentLog: 'घटना आर अलर्ट लॉग',
    maintenanceTab: 'मरम्मत कार्यक्रम',
    analyticsTab: 'जिलावार हिसाब आर बचत',
    simulatorTab: 'ESP32 सिम्युलेटर टेस्ट',
    totalUnits: 'गोटा इकाई',
    safeUnits: 'बेस दाः इकाई',
    unsafeUnits: 'का बेस इकाई',
    offlineUnits: 'ऑफलाइन इकाई',
    purifiedToday: 'तिसिंग बाटल साफा दाः',
    targetVolume: 'दैनिक लक्ष्य',
    exportCsv: 'CSV रिपोर्ट डाउनलोड',
    acknowledge: 'अलर्ट नेल केदा',
    resolve: 'समाधान होबाएना',
    logMaintenance: 'मरम्मत दर्ज मे',
    costPerLitre: 'प्रति लीटर खर्च',
    waterRecovery: 'दाः बचाव हिसाब',
    co2Saved: 'सोलर कार्बन बचत',
    login: 'विभागीय लॉगिन',
    logout: 'लॉगआउट',
    selectUnit: 'इकाई बाछाव मे',
    searchPlaceholder: 'जिला, प्रखंड बा हातु खोज मे...',

    // Super Simple Citizen View Keys (Ho)
    selectedWaterPoint: 'बाछाव दाः जायगा',
    stationCode: 'इकाई कोड',
    safeWaterHero: '१००% साफा आर नु लेका बेस दाः',
    unsafeWaterHero: 'सावधान! दाः का नुएय',
    offlineWaterHero: 'स्टेशन ऑफलाइन मेनाः',
    safeHeroSubtitle: 'ने दाः अडी बेस आर हेबड़ गेया। सबे नु दाड़ेया।',
    unsafeHeroSubtitle: 'मशीन दाः साफा ताना। तनी तांगी मे।',
    offlineHeroSubtitle: 'मरम्मत लागीत् ऑफलाइन मेनाः।',
    listenAudio: '🔊 आवाज़ ते आयुम मे',
    howIsWaterTitle: 'दाः चिलका मेनाः? (सरल कजी)',
    howIsWaterSubtitle: 'हातु दिसुम होड़ो को ल़ागित् आसान बात',
    simpleViewBtn: '😊 आसान दृश्य',
    detailedViewBtn: '📊 मीटर नंबर',
    clarityTitle: 'साफ़-सफाई',
    clarityBadge: 'एकदम साफ़',
    clarityHeading: 'आईना लेका साफा',
    clarityDesc: 'दाः रे हसा-धूरी बानोःआ।',
    tasteTitle: 'हेबड़ आर मिनरल (TDS)',
    tasteBadge: 'हेबड़ दाः',
    tasteHeading: 'हेबड़ आर बेस दाः',
    tasteDesc: 'होड़मो ल़ागित् दरकारी मिनरल मेनाः।',
    balanceTitle: 'संतुलन (pH)',
    balanceBadge: 'संतुलित',
    balanceHeading: 'का जोजो, का तितता - बेस गेया',
    balanceDesc: 'लाज आर हाजमा ल़ागित् अडी बेस।',
    freshnessTitle: 'ताजगी आर रयाड़',
    freshnessBadge: 'ताज़ा दाः',
    freshnessHeading: 'नु लेका रयाड़ ताज़ा',
    freshnessDesc: 'सोलर मोटर ते ओडोल ताज़ा दाः।',
    rulesTitle: 'दाः नु रियाः ३ आसान नियम',
    rule1Title: '१. हरियर बोर्ड नेलेमे',
    rule1Desc: 'चेतान रे हरियर सिग्नल नेलोः रे दाः लुमे।',
    rule2Title: '२. साफ़ बर्तन अगुइमे',
    rule2Desc: 'ओड़ाः ते धोवल बोतल बा बाल्टी अगुइमे।',
    rule3Title: '३. सोझे नुइमे (हेडे़ज का दरकार)',
    rule3Desc: 'ने दाः सोलर फ़िल्टर ते १००% साफा गेया।',
    weeklyTitle: 'पाछू ७ दिन रे दाः चिलका ताइकेना?',
    pureLabel: 'साफा',
    impureLabel: 'का साफा',
    loadingHistory: 'इतिहास लोड होवतना...',
    caretakerTitle: 'हातु रियाः जल सहिया',
    caretakerDesc: 'हातु रे दाः केंद्र नेल-जतन दीदी।',
    callJalSahiya: 'जल सहिया के फ़ोन लगावेमे',
    nearestWaterTitle: 'सुर रियाः बेस दाः केंद्र (नक्शा)',
    nearestWaterSubtitle: 'प्रखंड रियाः चालू बेस दाः केंद्र:',
    selectLocationTitle: 'अपन जायगा बाछाव मे (Select Location)',
    selectLocationSubtitle: 'अपन जिला बा प्रखंड रे क्लिक मे, एना जायगा रेयाः लाइव दाः डेटा तुरंत नेलोःआ:',
    autoDetectBtn: '📍 सुर रेयाः दाः जायगा खोज मे',
    detecting: 'जायगा खोजोः ताना...',
    stationsLabel: 'दाः जायगा',
    speakingAudio: 'कजी ताना...',
    tdsMetricDesc: 'दरकारी मिनरल (BIS सीमा ≤ 500)',
    phMetricDesc: 'संतुलित pH (BIS 6.5 – 8.5)',
    turbidityMetricDesc: 'आईना लेका साफा (BIS सीमा ≤ 1.0)',
    tempMetricDesc: 'नु लेका रयाड़ ताज़ा (10 - 35°C)'
  },
  kru: {
    portalTitle: 'स्मार्ट अम चोक्खा आर जांच पोर्टल (Kurukh)',
    deptTitle: 'ओन्ना अम आर सफई विभाग • झारखण्ड सरकार',
    sihRef: 'समस्या: SIH26040 | नवीकरणीय ऊर्जा आर IoT',
    publicView: 'आलर / पड्डा दृश्य',
    phedView: 'सरकारी दफ्तर पोर्टल',
    liveStream: 'लाइव IoT टेलीमेट्री चालू',
    offlineStream: 'ऑफलाइन / बफ़र मोड',
    safe: 'ओन्ना गे बेस / चोक्खा अम',
    unsafe: 'मल्ला बेस अम - अमके ओन',
    offline: 'ऑफलाइन',
    lastChecked: 'टुंगु जांच बेरा',
    unitLocation: 'अम जायगा',
    parameters: 'अम जांच पैमाना (BIS 10500)',
    phLabel: 'pH मान',
    tdsLabel: 'घुलल पदार्थ (TDS)',
    turbidityLabel: 'गदलापन',
    tempLabel: 'अम तापमान',
    safeVerdict: 'ओन्ना गे चोक्खा रही',
    unsafeVerdict: 'खतरा दायरा ती बेसी',
    warningVerdict: 'होशियार दायरा मंझिम',
    history7Days: 'बीतल ७ उल्ला ता अम हाल',
    nearbyUnits: 'हेद्दे ता बेस अम केंद्र',
    publicAlerts: 'पड्डा गे सूचना',
    filterHealth: 'फ़िल्टर हाल',
    cartridgeInstalled: 'फ़िल्टर लगाबा बेरा',
    lastMaintenance: 'टुंगु मरम्मत बेरा',
    recirculationLog: 'स्वचालित पुनर्चक्रण लॉग',
    inletVsOutlet: 'कच्चा अम बनाम चोक्खा अम तुलना',
    inlet: 'कच्चा अम (Inlet)',
    outlet: 'चोक्खा अम (Outlet)',
    fleetOverview: 'गोटा राज्य इकाई सूची',
    incidentLog: 'घटना आर अलर्ट खाता',
    maintenanceTab: 'मरम्मत कार्यक्रम',
    analyticsTab: 'जिलावार हिसाब आर बचत',
    simulatorTab: 'ESP32 सिम्युलेटर टेस्ट',
    totalUnits: 'गोटा इकाई संख्या',
    safeUnits: 'चोक्खा अम इकाई',
    unsafeUnits: 'मल्ला बेस इकाई',
    offlineUnits: 'ऑफलाइन इकाई',
    purifiedToday: 'इन्नो बाटल चोक्खा अम',
    targetVolume: 'दैनिक टारगेट',
    exportCsv: 'CSV रिपोर्ट डाउनलोड नना',
    acknowledge: 'अलर्ट एरा',
    resolve: 'बेस मंज्जा',
    logMaintenance: 'मरम्मत दर्ज नना',
    costPerLitre: 'प्रति लीटर खर्च',
    waterRecovery: 'अम बचाव हिसाब',
    co2Saved: 'सोलर कार्बन बचत',
    login: 'विभागीय लॉगिन',
    logout: 'लॉगआउट',
    selectUnit: 'इकाई चुनके',
    searchPlaceholder: 'जिला, प्रखंड या पड्डा बेद्दा...',

    // Super Simple Citizen View Keys (Kurukh)
    selectedWaterPoint: 'चुनल अम केंद्र',
    stationCode: 'इकाई कोड',
    safeWaterHero: '१००% चोक्खा आर ओन्ना गे बेस अम',
    unsafeWaterHero: 'सावधान! अम अमके ओन',
    offlineWaterHero: 'स्टेशन ऑफलाइन रही',
    safeHeroSubtitle: 'ई अम एकदम चोक्खा, मीठा आर बेस रही। सबे सीधे ओन सकनर।',
    unsafeHeroSubtitle: 'मशीन अम साफ़ करे लागी। तनी थमहा।',
    offlineHeroSubtitle: 'मरम्मत गे स्टेशन ऑफलाइन रही।',
    listenAudio: '🔊 आवाज़ ती मेना',
    howIsWaterTitle: 'अम एकसन रही? (सरल बात नू)',
    howIsWaterSubtitle: 'पड्डा आलर आर कुक्को-कुइयाँ गे आसान बात',
    simpleViewBtn: '😊 आसान दृश्य',
    detailedViewBtn: '📊 मीटर नंबर',
    clarityTitle: 'साफ़-सफाई',
    clarityBadge: 'एकदम साफ़',
    clarityHeading: 'आईना लेका चोक्खा',
    clarityDesc: 'अम नू ककड़ो धूर-माटी मल्ला।',
    tasteTitle: 'स्वाद आर मिनरल (TDS)',
    tasteBadge: 'मीठा अम',
    tasteHeading: 'मीठा आर बेस अम',
    tasteDesc: 'काया गे दरकारी मिनरल रही।',
    balanceTitle: 'संतुलन (pH)',
    balanceBadge: 'संतुलित',
    balanceHeading: 'मल्ला खट्टा, मल्ला कड़वा - एकदम ठीक',
    balanceDesc: 'कुल आर हाजमा गे सबले बेस।',
    freshnessTitle: 'ताजगी आर ठंडा',
    freshnessBadge: 'ताज़ा अम',
    freshnessHeading: 'ओन्ना लायक शीतल ताज़ा',
    freshnessDesc: 'सोलर मोटर ती निकलल ताज़ा अम।',
    rulesTitle: 'अम ओन्ना ता ३ आसान नियम',
    rule1Title: '१. हरियर बोर्ड एरा',
    rule1Desc: 'मेया हरियर सिग्नल एरा, तब्बे अम उना।',
    rule2Title: '२. चोक्खा बर्तन लाबा',
    rule2Desc: 'एड़पा ती धोवल बोतल या बाल्टी लाबा।',
    rule3Title: '३. सोझे ओन (उबालेक मल्ला)',
    rule3Desc: 'ई अम सोलर फ़िल्टर ती १००% चोक्खा रही।',
    weeklyTitle: 'बीतल ७ उल्ला नू अम एकसन रहचा?',
    pureLabel: 'चोक्खा',
    impureLabel: 'मल्ला चोक्खा',
    loadingHistory: 'इतिहास लोड होवत रही...',
    caretakerTitle: 'पड्डा ता जल सहिया',
    caretakerDesc: 'पड्डा नू अम केंद्र केर देख-रेख केर दीदी।',
    callJalSahiya: 'जल सहिया के फ़ोन लगाके',
    nearestWaterTitle: 'हेद्दे ता दूसर बेस अम (नक्शा)',
    nearestWaterSubtitle: 'प्रखंड नू चालू बेस अम केंद्र:',
    selectLocationTitle: 'अपन जायगा चुनके (Select Location)',
    selectLocationSubtitle: 'अपन जिला या प्रखंड नू क्लिक नना, आ जायगा ता लाइव अम डेटा तुरंत एरा:',
    autoDetectBtn: '📍 हेद्दे ता अम केंद्र बेद्दा',
    detecting: 'जायगा बेद्दा लागल...',
    stationsLabel: 'अम केंद्र',
    speakingAudio: 'कच्छा लागल...',
    tdsMetricDesc: 'दरकारी मिनरल (BIS सीमा ≤ 500)',
    phMetricDesc: 'संतुलित pH (BIS 6.5 – 8.5)',
    turbidityMetricDesc: 'आईना लेका चोक्खा (BIS सीमा ≤ 1.0)',
    tempMetricDesc: 'ओन्ना लायक शीतल ताज़ा (10 - 35°C)'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('astra_lang') || 'en');

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('astra_lang', newLang);
  };

  const toggleLanguage = () => {
    const next = lang === 'en' ? 'hi' : 'en';
    changeLanguage(next);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations.en?.[key] || translations.hi?.[key] || key;
  };

  const currentLanguageObj = SUPPORTED_LANGUAGES.find(l => l.code === lang) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, toggleLanguage, t, currentLanguageObj, supportedLanguages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
